import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppWrapper } from "@/context";
import SideBar from "@/components/SideBar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shoden",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen w-screen">
        <AppWrapper>
          <div className="h-full w-full flex flex-col">
            <div className="flex flex-row flex-grow">
              <SideBar />
              {children}
            </div>
            <Footer />
          </div>
        </AppWrapper>
      </body>
    </html>
  );
}
